name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  testunit:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: bash ./gradlew test

  testui:
    name: Run UI Tests
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

  apk:
    name: Generate signed APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble app release APK
        run: bash ./gradlew assembleRelease

      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
